apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-go-app
spec:
  replicas: 3 ## set the replicas here 
  selector:
    matchLabels:
      app: simple-go-app
  template:
    metadata:
      labels:
        app: simple-go-app
    spec:
      securityContext:
        runAsUser: 1001 ## run as non-root user
      containers:
      - name: simple-go-app
        image: ghcr.io/govindkailas/simple-go-app:main
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        resources: ## run with a minimum resource
          limits: ## max limits
            cpu: "100m"
            memory: "50Mi"
          requests: ## pod will start with this
            cpu: "50m"
            memory: "25Mi"
        securityContext:
          allowPrivilegeEscalation: false    
        env: ## setting up env variables from downward api, more here, https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: simple-go-app-svc
spec:
  type: LoadBalancer ## change to ClusterIP or NodePort if needed. 
  selector:
    app: simple-go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
