jobs:
  automerge: 
    name: Automerge Dependabot PRs
    if: github.event_name == 'pull_request' && github.event.pull_request.user.type == 'Bot' && github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Automerge Dependabot PRs
      uses: peter-evans/automerge-action@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        merge_method: squash
