- name: Automerge Dependabot PRs
        if: github.event_name == 'pull_request' && github.event.pull_request.user.type == 'Bot' && github.event.pull_request.user.login == 'dependabot[bot]'
        uses: peter-evans/automerge-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash