on:
  pull_request:
    types: [opened]
    branches:
      - main  # Or your default branch
jobs:
  automerge: 
    name: Automerge Dependabot PRs
    if: github.event_name == 'pull_request' && github.event.pull_request.user.type == 'Bot' && github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Automerge Dependabot PRs
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        merge_method: squash
